<?php
/**
 * Contains Gimi\myFormsTools\PckmyFields\myEmail.
 */

namespace Gimi\myFormsTools\PckmyFields;


use Gimi\myFormsTools\PckmySessions\myAutoSessions;
use Gimi\myFormsTools\PckmySessions\mySessions;
use Gimi\myFormsTools\PckmyUtils\myMailFake;

class myEmail extends myText  {
/**
 * @ignore
 */	
protected $restrizioni_check=array();
protected $dominiFake=array(
  '0-mail.com',
  '0815.ru',
  '0clickemail.com',
  '0wnd.net',
  '0wnd.org',
  '10minutemail.com',
  '20minutemail.com',
  '2prong.com',
  '30minutemail.com',
  '33mail.com',
  '3d-painting.com',
  '4warding.com',
  '4warding.net',
  '4warding.org',
  '60minutemail.com',
  '675hosting.com',
  '675hosting.net',
  '675hosting.org',
  '6url.com',
  '75hosting.com',
  '75hosting.net',
  '75hosting.org',
  '7tags.com',
  '9ox.net',
  'a-bc.net',
  'afrobacon.com',
  'ajaxapp.net',
  'amilegit.com',
  'amiri.net',
  'amiriindustries.com',
  'anonbox.net',
  'anonymbox.com',
  'antichef.com',
  'antichef.net',
  'antispam.de',
  'armyspy.com',
  'azmeil.tk',
  'baxomale.ht.cx',
  'beefmilk.com',
  'binkmail.com',
  'bio-muesli.net',
  'bobmail.info',
  'bodhi.lawlita.com',
  'bofthew.com',
  'brefmail.com',
  'broadbandninja.com',
  'bsnow.net',
  'bugmenot.com',
  'bumpymail.com',
  'casualdx.com',
  'centermail.com',
  'centermail.net',
  'chogmail.com',
  'choicemail1.com',
  'cool.fr.nf',
  'correo.blogos.net',
  'cosmorph.com',
  'courriel.fr.nf',
  'courrieltemporaire.com',
  'cubiclink.com',
  'curryworld.de',
  'crazymailing.com',
  'cust.in',
  'cuvox.de',
  'dacoolest.com',
  'dandikmail.com',
  'dayrep.com',
  'deadaddress.com',
  'deadspam.com',
  'despam.it',
  'despammed.com',
  'devnullmail.com',
  'dfgh.net',
  'digitalsanctuary.com',
  'discardmail.com',
  'discardmail.de',
  'disposableaddress.com',
  'disposeamail.com',
  'disposemail.com',
  'dispostable.com',
  'dm.w3internet.co.ukexample.com',
  'dodgeit.com',
  'dodgit.com',
  'dodgit.org',
  'donemail.ru',
  'dontreg.com',
  'dontsendmespam.de',
  'drdrb.com',
  'dump-email.info',
  'dumpandjunk.com',
  'dumpmail.de',
  'dumpyemail.com',
  'e4ward.com',
  'einrot.com',
  'email60.com',
  'emaildienst.de',
  'emailias.com',
  'emailigo.de',
  'emailinfive.com',
  'emailmiser.com',
  'emailsensei.com',
  'emailtemporario.com.br',
  'emailto.de',
  'emailwarden.com',
  'emailx.at.hm',
  'emailxfer.com',
  'emeil.in',
  'emeil.ir',
  'emz.net',
  'enterto.com',
  'ephemail.net',
  'etranquil.com',
  'etranquil.net',
  'etranquil.org',
  'explodemail.com',
  'fakeinbox.com',
  'fakeinformation.com',
  'fastacura.com',
  'fastchevy.com',
  'fastchrysler.com',
  'fastkawasaki.com',
  'fastmazda.com',
  'fastmitsubishi.com',
  'fastnissan.com',
  'fastsubaru.com',
  'fastsuzuki.com',
  'fasttoyota.com',
  'fastyamaha.com',
  'filzmail.com',
  'fizmail.com',
  'fleckens.hu',
  'fr33mail.info',
  'frapmail.com',
  'front14.org',
  'fux0ringduh.com',
  'garliclife.com',
  'get1mail.com',
  'get2mail.fr',
  'getonemail.com',
  'getonemail.net',
  'ghosttexter.de',
  'girlsundertheinfluence.com',
  'gishpuppy.com',
  'gowikibooks.com',
  'gowikicampus.com',
  'gowikicars.com',
  'gowikifilms.com',
  'gowikigames.com',
  'gowikimusic.com',
  'gowikinetwork.com',
  'gowikitravel.com',
  'gowikitv.com',
  'great-host.in',
  'greensloth.com',
  'gsrv.co.uk',
  'guerillamail.biz',
  'guerillamail.com',
  'guerillamail.net',
  'guerillamail.org',
  'guerrillamail.biz',
  'guerrillamail.com',
  'guerrillamail.de',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamailblock.com',
  'gustr.com',
  'h.mintemail.com',
  'h8s.org',
  'haltospam.com',
  'hatespam.org',
  'hidemail.de',
  'hochsitze.com',
  'hotpop.com',
  'hulapla.de',
  'ieatspam.eu',
  'ieatspam.info',
  'ihateyoualot.info',
  'iheartspam.org',
  'imails.info',
  'inbax.tk',
  'inboxalias.com',
  'inboxclean.com',
  'inboxclean.org',
  'incognitomail.com',
  'incognitomail.net',
  'incognitomail.org',
  'insorg-mail.info',
  'ipoo.org',
  'irish2me.com',
  'iwi.net',
  'jetable.com',
  'jetable.fr.nf',
  'jetable.net',
  'jetable.org',
  'jnxjn.com',
  'jourrapide.com',
  'junk1e.com',
  'kasmail.com',
  'kaspop.com',
  'keepmymail.com',
  'killmail.com',
  'killmail.net',
  'kir.ch.tc',
  'klassmaster.com',
  'klassmaster.net',
  'klzlk.com',
  'koszmail.pl',
  'kulturbetrieb.info',
  'kurzepost.de',
  'letthemeatspam.com',
  'lhsdv.com',
  'lifebyfood.com',
  'link2mail.net',
  'litedrop.com',
  'lol.ovpn.to',
  'lookugly.com',
  'lopl.co.cc',
  'lortemail.dk',
  'lr78.com',
  'm4ilweb.info',
  'maboard.com',
  'mail-temporaire.fr',
  'mail.by',
  'mail.mezimages.net',
  'mail2rss.org',
  'mail333.com',
  'mail4trash.com',
  'mailbidon.com',
  'mailblocks.com',
  'mailcatch.com',
  'maildrop.cc',
  'maileater.com',
  'mailexpire.com',
  'mailfa.tk',
  'mailfreeonline.com',
  'mailin8r.com',
  'mailinater.com',
  'mailinator.com',
  'mailinator.net',
  'mailinator2.com',
  'mailincubator.com',
  'mailme.ir',
  'mailme.lv',
  'mailmetrash.com',
  'mailmoat.com',
  'mailnator.com',
  'mailnesia.com',
  'mailnull.com',
  'mailshell.com',
  'mailsiphon.com',
  'mailslite.com',
  'mailzilla.com',
  'mailzilla.org',
  'mbx.cc',
  'mega.zik.dj',
  'meinspamschutz.de',
  'meltmail.com',
  'messagebeamer.de',
  'mierdamail.com',
  'mintemail.com',
  'moburl.com',
  'moncourrier.fr.nf',
  'monemail.fr.nf',
  'monmail.fr.nf',
  'msa.minsmail.com',
  'mt2009.com',
  'mx0.wwwnew.eu',
  'mycleaninbox.net',
  'mypartyclip.de',
  'myphantomemail.com',
  'myspaceinc.com',
  'myspaceinc.net',
  'myspaceinc.org',
  'myspacepimpedup.com',
  'myspamless.com',
  'mytrashmail.com',
  'neomailbox.com',
  'nepwk.com',
  'nervmich.net',
  'nervtmich.net',
  'netmails.com',
  'netmails.net',
  'netzidiot.de',
  'neverbox.com',
  'no-spam.ws',
  'nobulk.com',
  'noclickemail.com',
  'nogmailspam.info',
  'nomail.xl.cx',
  'nomail2me.com',
  'nomorespamemails.com',
  'nospam.ze.tc',
  'nospam4.us',
  'nospamfor.us',
  'nospamthanks.info',
  'notmailinator.com',
  'nowmymail.com',
  'nurfuerspam.de',
  'nus.edu.sg',
  'nwldx.com',
  'objectmail.com',
  'obobbo.com',
  'oneoffemail.com',
  'onewaymail.com',
  'online.ms',
  'oopi.org',
  'ordinaryamerican.net',
  'otherinbox.com',
  'ourklips.com',
  'outlawspam.com',
  'ovpn.to',
  'owlpic.com',
  'pancakemail.com',
  'pimpedupmyspace.com',
  'pjjkp.com',
  'politikerclub.de',
  'poofy.org',
  'pookmail.com',
  'privacy.net',
  'proxymail.eu',
  'prtnx.com',
  'putthisinyourspamdatabase.com',
  'punkass.com',
  'qq.com',
  'quickinbox.com',
  'rcpt.at',
  'recode.me',
  'recursor.net',
  'regbypass.com',
  'regbypass.comsafe-mail.net',
  'rejectmail.com',
  'rhyta.com',
  'rklips.com',
  'rmqkr.net',
  'rppkn.com',
  'rtrtr.com',
  's0ny.net',
  'safe-mail.net',
  'safersignup.de',
  'safetymail.info',
  'safetypost.de',
  'sandelf.de',
  'saynotospams.com',
  'selfdestructingmail.com',
  'sendspamhere.com',
  'sharklasers.com',
  'shiftmail.com',
  'shitmail.me',
  'shortmail.net',
  'sibmail.com',
  'skeefmail.com',
  'slaskpost.se',
  'slopsbox.com',
  'smellfear.com',
  'snakemail.com',
  'sneakemail.com',
  'sofimail.com',
  'sofort-mail.de',
  'sogetthis.com',
  'soodonims.com',
  'spam.la',
  'spam.su',
  'spam4.me',
  'spamavert.com',
  'spambob.com',
  'spambob.net',
  'spambob.org',
  'spambog.com',
  'spambog.de',
  'spambog.ru',
  'spambox.info',
  'spambox.irishspringrealty.com',
  'spambox.us',
  'spamcannon.com',
  'spamcannon.net',
  'spamcero.com',
  'spamcon.org',
  'spamcorptastic.com',
  'spamcowboy.com',
  'spamcowboy.net',
  'spamcowboy.org',
  'spamday.com',
  'spamex.com',
  'spamfree24.com',
  'spamfree24.de',
  'spamfree24.eu',
  'spamfree24.info',
  'spamfree24.net',
  'spamfree24.org',
  'spamgourmet.com',
  'spamgourmet.net',
  'spamgourmet.org',
  'spamherelots.com',
  'spamhereplease.com',
  'spamhole.com',
  'spamify.com',
  'spaminator.de',
  'spamkill.info',
  'spaml.com',
  'spaml.de',
  'spammotel.com',
  'spamobox.com',
  'spamoff.de',
  'spamslicer.com',
  'spamspot.com',
  'spamthis.co.uk',
  'spamthisplease.com',
  'spamtrail.com',
  'speed.1s.fr',
  'supergreatmail.com',
  'supermailer.jp',
  'superrito.com',
  'suremail.info',
  'tagyourself.com',
  'teewars.org',
  'teleworm.com',
  'teleworm.us',
  'tempalias.com',
  'tempe-mail.com',
  'tempemail.biz',
  'tempemail.com',
  'tempinbox.co.uk',
  'tempinbox.com',
  'tempmail.it',
  'tempemail.net',
  'tempmail2.com',
  'tempomail.fr',
  'temporarily.de',
  'temporarioemail.com.br',
  'temporaryemail.net',
  'temporaryforwarding.com',
  'temporaryinbox.com',
  'thanksnospam.info',
  'thankyou2010.com',
  'thisisnotmyrealemail.com',
  'throwawayemailaddress.com',
  'tilien.com',
  'tmailinator.com',
  'tradermail.info',
  'trash-amil.com',
  'trash-mail.at',
  'trash-mail.com',
  'trash-mail.de',
  'trash2009.com',
  'trashemail.de',
  'trashmail.at',
  'trashmail.com',
  'trashmail.de',
  'trashmail.me',
  'trashmail.net',
  'trashmail.org',
  'trashmail.ws',
  'trashmailer.com',
  'trashymail.com',
  'trashymail.net',
  'trillianpro.com',
  'turual.com',
  'twinmail.de',
  'tyldd.com',
  'uggsrock.com',
  'upliftnow.com',
  'uplipht.com',
  'venompen.com',
  'veryrealemail.com',
  'viditag.com',
  'viewcastmedia.com',
  'viewcastmedia.net',
  'viewcastmedia.org',
  'webm4il.info',
  'wegwerfadresse.de',
  'wegwerfemail.de',
  'wegwerfmail.de',
  'wegwerfmail.net',
  'wegwerfmail.org',
  'wetrainbayarea.com',
  'wetrainbayarea.org',
  'wh4f.org',
  'whatpaas.com',
  'whyspam.me',
  'willselfdestruct.com',
  'winemaven.info',
  'wronghead.com',
  'wuzup.net',
  'wuzupmail.net',
  'www.e4ward.com',
  'www.gishpuppy.com',
  'www.mailinator.com',
  'wwwnew.eu',
  'xagloo.com',
  'xemaps.com',
  'xents.com',
  'xmaily.com',
  'xoxy.net',
  'yep.it',
  'yogamaven.com',
  'yopmail.com',
  'yopmail.it',
  'yopmail.fr',
  'yopmail.net',
  'ypmail.webarnak.fr.eu.org',
  'yuurok.com',
  'zehnminutenmail.de',
  'zippymail.info',
  'zoaxe.com',
  'zoemail.org');	
/**
  *
  * 
  * @param	 string $nome E' il nome del campo
  * @param	 string $valore Valore da assegnare come default
  * @param	 string $classe e' la classe css da utilizzare
  */
   public function __construct($nome,$valore='',$classe='') {
		parent::__construct($nome,$valore,$classe);
	    $this->set_regexp('^[-_a-zA-Z0-9]+[-\\._a-zA-Z0-9]*[a-zA-Z0-9_\\+\\-]+@[a-zA-Z0-9\-]{1,}[-_\.a-zA-Z0-9]{0,}\.(com|edu|net|org|biz|info|it|int|gov|eu|name|mil|mobi|aero|asia|jobs|museum|srl|[a-zA-Z]{2})$',"non è in formato corretto");
		$this->set_MyType('MyEmail');
		$this->set_MaiMin('minuscolo');
		$this->set_restrizioni_check();
  }

  protected function html5Settings($attrs=array()){
      $attrs['type']='email';
      myField::html5Settings($attrs);
  }



  /** @ignore */
   protected function get_errore_diviso_singolo(){
    $esito=parent::get_errore_diviso_singolo();
    if ($esito) return $esito;
    if(!$this->get_value()) return;
    if(is_callable('filter_var') && !filter_var(strtolower($this->get_value()), FILTER_VALIDATE_EMAIL)) return 'non è in formato corretto';
   	if(!$esito /*&& $_SERVER['LOCAL_ADDR']!='127.0.0.1' */&& $this->restrizioni_check && $this->get_value())
  	           { $dominio=explode('@',strtolower($this->get_value()),2);
  	             $dominio=$dominio[1];
  	             if($this->restrizioni_check[2]==true && myMailFake::isFake($this->get_value())) return 'non appartiene ad un dominio affidabile';
  	             elseif($this->restrizioni_check[1] || $this->restrizioni_check[0])
  	                     { 
  	                       $dominiGlobal=myAutoSessions::get_Istanza('myEmailDomini');
              	 	       $domini=new mySessions('myEmailDomini');
              	 	       $done=$domini->get('verificati');
              	 	       if(!is_array($done)) $done=array();
              	 	       if($dominiGlobal) 
              	 	                   {
              	 	                     $doneGlobal=$dominiGlobal->get('verificati');
              	 	                     if(!is_array($doneGlobal)) $doneGlobal=array();
              	 	                   }
                           
                           $done=array_merge($done,$doneGlobal);
                           if(isset($done[$dominio])) $valido=$done[$dominio];
                                else{$valido=null;
                                     $mx=$rc=array();
                      				 if($this->restrizioni_check[1]) 
                      				  	 			  {//richiesto specificatamente mx
                      				   			      $mx=@dns_get_record($dominio,DNS_MX+DNS_A);
                      				   			      if(is_array($mx)) 
                      				   			            {
                      				   			             foreach ($mx as $rc) if($rc['type']=='MX') $valido=true;
                      				   			             if(!$valido && count($mx)==1) $valido=true;
                      				   			            }
                      				   			      if($valido===null) {
                      				 				                     if($mx===false || count($mx)>0) $valido=true; //se richiesta fallita per indisponibilità dns o esistono i record mx ok
                      				 				  					                     	   else  $valido=false;
                      				   			                         }
                      				  	 			  }
                          				 elseif($this->restrizioni_check[0]) 
                          				              { 
                      				 				  $rc=@dns_get_record($dominio);
                      				 				  if($rc===false || count($rc)>0) $valido=true; //se richiesta fallita per indisponibilità dns o esistono i record mx ok
                      				 				  							else  $valido=false;
                      				  	 			  }	
                                     $done[$dominio]=$valido;
                                     $domini->set('verificati',$done,true);
                                     if($dominiGlobal)  $dominiGlobal->set('verificati',$done,true);
                                     }
                          if(isset($valido) && !$valido) return 'non è accettabile';
  	                      }
  	          }
  	return $esito;
  }

  /**
   * Permette di rendere il check_errore piu' o meno restrittivo
   * @param boolean $VerificaRecordDX  Verifica l'esistenza di un record DX relativo a server mail
   * @param boolean $VerificaDNS       Verifica sulla rete che il dominio sia valido
   * @param boolean $DominiFake       Verifica il dominio sia censito come non usa e getta
   */
   public function set_restrizioni_check($VerificaRecordDX=true,$VerificaDNS=true,$DominiFake=true){
  	$this->restrizioni_check=array($VerificaDNS,$VerificaRecordDX,$DominiFake);
  	  	if($DominiFake) myMailFake::refresh();
  	return $this;
  }


  




  

}